#!/bin/bash
set -x

hugo

# Configure Git to only push the current branch
git config --global push.default simple

# Remove .gitignore and replace with the production version
# rm -f .gitignore
# cp scripts/prodignore .gitignore
# cat .gitignore

# Add the Linode production server as a remote repository
git remote add production ssh://travis@172.104.15.177:/home/travis/hugobare.git

# Add and commit all the static files generated by the Gatsby build
git add . && git commit -m "Hugo build"

# Push all changes to the Linode production server
git push -f production HEAD:refs/heads/master

